$("document").ready(function(){
   $(".readmore").click(function(e){
    e.preventDefault();
    $("#moretext").toggle("slow");
    $(".readless").show();
    $(".readmore").hide();   
   });
    $(".readless").click(function(e){
    e.preventDefault();
    $("#moretext").toggle("slow");
    $(".readmore").show();
    $(".readless").hide();   
   });
    $(".secondreadmore").click(function(e){
    e.preventDefault();
    $("#secondmoretext").toggle("slow");
    $(".secondreadless").show();
    $(".secondreadmore").hide();   
   });
    $(".secondreadless").click(function(e){
    e.preventDefault();
    $("#secondmoretext").toggle("slow");
    $(".secondreadmore").show();
    $(".secondreadless").hide();   
   });
    $(".learnmore").click(function(e){
    e.preventDefault();
    $("#aboutmore").toggle("slow");
    $(".learnless").show();
    $(".learnmore").hide();   
   });
    $(".learnless").click(function(e){
    e.preventDefault();
    $("#aboutmore").toggle("slow");
    $(".learnmore").show();
    $(".learnless").hide();   
   });
});
